```{r, fig.width=7.5, fig.height=4.5}
df %>% 
    filter(considered) %>% 
    ggplot(aes(evaluation)) + 
        geom_bar(aes(fill=control), alpha=0.7, position="identity") +
        control_colors + wrap_   scenario + 
        labs(fill="considered by", y="N")
```

```{r, fig.width=7.5, fig.height=4.5}
df %>% 
    group_by(control, scenario, evaluation) %>% 
    summarise(y=sum(considered) - sum(accessibility)) %>% 
    ggplot(aes(evaluation, y)) + 
        geom_line(aes(color=control), stat="identity", alpha=0.7, position="identity") +
        control_colors + wrap_scenario + 
        labs(fill="considered by", y="proportion")
```

```{r, fig.width=7.5, fig.height=4.5}
df %>% 
    ggplot(aes(evaluation, y=..prop..)) + 
    geom_bar(data=filter(df, outcome != "UNK"), alpha=1, fill="gray50", position="identity") +
    geom_bar(aes(fill=control), data=filter(df, considered), alpha=0.7, position="identity") +
    control_colors + wrap_scenario + 
    labs(fill="considered by", y="proportion")
```

```{r}
unk_df %>% 
    filter(scenario == "animals (intimate)") %>% 
    filter(considered) %>% 
    filter(control == "high") %>% 
    select(wid,raw_outcome,outcome, evaluation) %>% 
    print(n=50)
```

```{r, fig.width=7.5, fig.height=10}
df %>% 
    group_by(scenario) %>% 
    mutate(outcome = fct_reorder(outcome, evaluation, .fun=mean)) %>% 
    ggplot(aes(evaluation, outcome)) +
        stat_summary(fun.data=mean_sdl, fun.args = list(mult = 1), color="gray") + 
        stat_summary(fun.data=mean_cl_boot) + 
        geom_vline(xintercept=0, linetype="dashed") +
        no_grid + ylab(NULL) +
        facet_wrap(~scenario, dir="h", ncol=2, scale="free_y")
```